# group_vars/family.yml

# ============================================================================
# Fonts
# ============================================================================

restore_fonts: false

# ============================================================================
# Applications
# ============================================================================

# Command Line Tools (Brew Formulae)
family_formula_apps: []

# GUI Applications (Brew Casks)
family_cask_apps:
  - google-chrome
  - plex
  - sonos

# Mac App Store (MAS)
family_mas_apps: []
  #- { id: 1570472288, name: 'Sketchbook Pro' }

# ============================================================================
# Dock Configuration
# ============================================================================

family_dock_apps:
  - path: "/Applications/Google Chrome.app"
  - path: "/System/Applications/Messages.app"
  - path: "/System/Applications/Notes.app"
  - path: "/System/Applications/Reminders.app"

family_dock_folders:
  - path: "~/Downloads"
    view: fan
    display: folder
    sort: dateadded

# ============================================================================
# Login Items
# ============================================================================

family_login_items: []

family_remove_login_items: []