# group_vars/family.yml

# Public SSH keys from personal backup
ssh_files:
  - { src: "../personal/id_ed25519.pub", dest: "id_ed25519.pub", mode: '0644' }
  - { src: "../personal/id_rsa.pub", dest: "id_rsa.pub", mode: '0644' }
  - { src: "../personal/authorized_keys", dest: "authorized_keys", mode: '0600' }

  
# Command Line Tools (Brew Formulae)
family_formula_apps: []

# GUI Applications (Brew Casks)
family_cask_apps:
  - google-chrome
  - plex
  - sonos

# Mac App Store (MAS)
family_mas_apps: []
  #- { id: 1570472288, name: 'Sketchbook Pro' }

family_dock_apps:
  - path: "/Applications/Google Chrome.app"
  - path: "/System/Applications/Messages.app"
  - path: "/System/Applications/Notes.app"
  - path: "/System/Applications/Reminders.app"

family_dock_folders:
  - path: "~/Downloads"
    view: fan
    display: folder
    sort: dateadded