# group_vars/personal.yml

# Personal gets full SSH keys (private + public) - MASTER
ssh_files:
  - { src: "id_ed25519", dest: "id_ed25519", mode: '0600' }
  - { src: "id_ed25519.pub", dest: "id_ed25519.pub", mode: '0644' }
  - { src: "id_rsa", dest: "id_rsa", mode: '0600' }
  - { src: "id_rsa.pub", dest: "id_rsa.pub", mode: '0644' }
  - { src: "config", dest: "config", mode: '0600' }
  - { src: "authorized_keys", dest: "authorized_keys", mode: '0600' }

  
# Command Line Tools (Brew Formulae)
personal_formula_apps:
  - exiftool
  - gnu-tar
  - immich-go
  - mkvtoolnix
  - starship
  - tree


# GUI Applications (Brew Casks)
personal_cask_apps:
  #- 4k-video-downloader
  - adobe-creative-cloud
  - angry-ip-scanner
  #- audacity ?
  - balenaetcher
  - brave-browser
  - visual-studio-code
  - blender
  - carbon-copy-cloner
  - discord
  - downie
  #- flux ??
  #- find-empty-folders
  - fontbase
  - fontforge-app
  - github
  - google-drive
  - heroic
  - imageoptim
  #- imazing DO I HAVE AN OLDER LICENSE??
  #- keka
  - loopback
  - lulu
  - mactracker
  - macwhisper
  - mediahuman-audio-converter
  #- mkvtools
  #- mkvtoolnix-app
  - opencore-patcher
  - platypus
  - plex
  - pronotes
  - qlmarkdown
  - raycast
  - sonos
  #- subler
  #- sublercli
  - superwhisper
  - synology-drive
  - the-unarchiver
  #- ultimate-vocal-remover


# Mac App Store (MAS)
personal_mas_apps:
  - { id: 1586435171, name: 'Actions' } #Actions for Apple Shortcuts
  #- { id: 1616831348, name: 'Affinity Designer 2' } DISCONTINUED
  #- { id: 1616822987, name: 'Affinity Photo 2' } DISCONTINUED
  # - { id: 1606941598, name: 'Affinity Publisher 2' } DISCONTINUED
  # - { id: 424390742, name: 'Compressor' } USE JOY INC ACCOUNT
  - { id: 1453273600, name: 'Data Jar' } # Data Store for Shortcuts
  - { id: 325206381, name: 'Flame Services Browser' }
  #- { id: 6443819966, name: 'IP Scanner' }
  # - { id: 524141863, name: 'Jump Desktop'} # tim@joy.inc app
  - { id: 1532597159, name: 'Mp3tag' }
  - { id: 1455214828, name: 'MQTT Explorer' }
  - { id: 603637384, name: 'Name Mangler 3' }
  - { id: 463362050, name: 'Photosweeper' }
  # - { id: 506088175, name: 'Pushover' } IPAD APP â€“ MANUAL INSTALL
  - { id: 1598580439, name: 'RAW Convertor' }
  - { id: 1550457805, name: 'Soro for Sonos' } # Control Sonos with Shortcuts
  - { id: 1481853033, name: 'Strongbox Pro' }
  - { id: 1475387142, name: 'Tailscale' }
  - { id: 1490879410, name: 'Trash Me' }
  # - { id: 1062679359, name: 'Typeface 4' }


# Apps to install via DMG/PKG 
personal_dmg_pkg_apps:
  - name: "Argest Backup"
    url: "/Volumes/backup_proxmox/macos/installers/Argest.dmg"
    volume: "Argest"

  - name: "Downie 4"
    url: "https://software.charliemonroe.net/downie/"
    volume: "Downie 4"

  - name: "Swinsian"
    url: "/Volumes/backup_proxmox/macos/installers/Swinsian.dmg"
    volume: "Swinsian 3.0.4"    

# Crossover
# Loopback
# Sketchup
# Swinsian
# Opentabletdriver


personal_manual_installs:
  - name: "DJI Assistant 2 (Ronin Series)"
    url: "https://www.dji.com/nz/downloads/softwares/dji-assistant-2-ronin-series"



# No longer used
# Creation Date Batch Change
# Quickres
# IWLTBAP LUT Generator


personal_dock_apps:
  - path: "/Applications/Bloom.app"
  - path: "/Applications/Brave Browser.app"
  - path: "/System/Applications/Messages.app"
  - path: "/System/Applications/Notes.app"
  - path: "/System/Applications/Reminders.app"
  - path: "/System/Applications/System Settings.app"

personal_dock_folders: []