# group_vars/video.yml

# ============================================================================
# Applications
# ============================================================================

# Command Line Tools (Brew Formulae)
video_formula_apps:
  - ffmpeg

# GUI Applications (Brew Casks)
video_cask_apps:
  - handbrake
  - ogdesign-eagle # Eagle.cool
  - jump-desktop-connect
  - iina
  - neofinder
  - slack

# Mac App Store (MAS)
video_mas_apps:
  - { id: 1160435653, name: 'AutoMounter' }
  - { id: 425264550, name: 'Blackmagic Speed Test' }
  #- { id: 424390742, name: 'Compressor' } # This requires the joy.inc App Store account
  #- { id: 1598580439, name: 'RAW Convertor' } Converts prores raw into cinemadng â€“ not needed anymore

# Apps to install via DMG/PKG
video_dmg_pkg_apps:
  - name: "Offshoot"
    url: "/Volumes/common/Software/Installers/filetransfer/OffShoot_20231123162111_v23.2.4b1533.dmg"
    volume: "OffShoot 23.2.4"

# ============================================================================
# Dock Configuration
# ============================================================================

video_dock_apps:
  - path: "/System/Applications/Slack.app"
  - path: "/System/Applications/System Settings.app"

video_dock_folders: []

# ============================================================================
# Login Items
# ============================================================================

video_login_items:
  - name: "AutoMounter"
    path: "/Applications/AutoMounter.app"
    hidden: true
  
  - name: "Tailscale"
    path: "/Applications/Tailscale.app"
    hidden: false

video_remove_login_items: []