---
- name: Install video formula apps
  community.general.homebrew:
    name: "{{ video_formula_apps }}"
    state: present
  when: video_formula_apps is defined and video_formula_apps | length > 0

- name: Install video cask apps
  community.general.homebrew_cask:
    name: "{{ video_cask_apps }}"
    state: present
  when: video_cask_apps is defined and video_cask_apps | length > 0

- name: Install video Mac App Store apps
  community.general.mas:
    id: "{{ item.id }}"
    state: present
  loop: "{{ video_mas_apps }}"
  when: video_mas_apps is defined and video_mas_apps | length > 0

- name: Install video apps from DMG/PKG files
  bepri.macos_tools.install:
    source: "{{ item.url }}"
    type: "{{ item.type | default(omit) }}"
    allow_untrusted: "{{ item.allow_untrusted | default(omit) }}"
  loop: "{{ video_dmg_pkg_apps }}"
  when: video_dmg_pkg_apps is defined and video_dmg_pkg_apps | length > 0
  vars:
    # This forces the task to use the same interpreter passed to the playbook
    ansible_python_interpreter: "{{ ansible_playbook_python }}"





- name: Display video manual install list
  debug:
    msg: "{{ video_manual_installs }}"
  when: video_manual_installs is defined and video_manual_installs | length > 0