# roles/family/tasks/main.yml


- name: Install family formula apps
  community.general.homebrew:
    name: "{{ family_formula_apps }}"
    state: present
  when: family_formula_apps is defined and family_formula_apps | length > 0

- name: Install family cask apps
  community.general.homebrew_cask:
    name: "{{ family_cask_apps }}"
    state: present
  when: family_cask_apps is defined and family_cask_apps | length > 0

- name: Install family Mac App Store apps
  community.general.mas:
    id: "{{ item.id }}"
    state: present
  loop: "{{ family_mas_apps }}"
  when: family_mas_apps is defined and family_mas_apps | length > 0

- name: Install family apps from DMG/PKG files
  include_tasks: "{{ playbook_dir }}/tasks/install_dmg.yml"
  vars:
    dmg_pkg_apps: "{{ family_dmg_pkg_apps }}"
  when: family_dmg_pkg_apps is defined and family_dmg_pkg_apps | length > 0
  
- name: Display family apps requiring manual installation
  debug:
    msg: |
      
      =====================================================
      ðŸ“‹ MANUAL INSTALLATION REQUIRED (FAMILY)
      =====================================================
      The following apps need to be installed manually:
      {% for app in family_manual_installs %}
      
      {{ loop.index }}. {{ app.name }}
         URL: {{ app.url }}
         {% if app.note is defined %}Note: {{ app.note }}{% endif %}
      {% endfor %}
      
      =====================================================
  when: family_manual_installs is defined and family_manual_installs | length > 0